### ISSUE TITLE
Failed to parse server response: invalid character 'C' looking for beginning of value.

### ISSUE THREAD

**Issue by FlaviuRadulescu** [rzrbld/adminio-api#14]
Hello,

I have an instalation of minio on 443 with a bucket.subdomain.domain.tld and when I am trying to start the adminio-api, I get the error:

{"error":"Failed to parse server response: invalid character 'C' looking for beginning of value."}

Can you please help me investigate what is the problem?

Thank you,
F

**Comment by rzrbld** [comment]
Hi, can you please provide how you run it? 
- as binary file
- as docker
- in k8s

do you specify all environment variables?
please note - you need an admin login and password to run adminio, not just any bucket key and secret.

**Comment by rzrbld** [comment]
@Niggl1999 hi, thanks)
- what version of minio do you use?
- is "workingAdminAccess" and "mySecretSecret" - it is a admin credentials? or it's a custom user with kind of "diagnostics" policy?

actually minio team build up their own web ui - https://github.com/minio/console

**Comment by Niggl1999** [comment]
* I run Minio version "RELEASE.2019-10-12T01-39-57z" in a FreeNAS 11.3 jail, although this is gonna change in 1-2 weeks when I migrate my minio to a debian+docker based setup
* The credentials are admin credentials

The console project by minio themselves looks promising, but I'm still interested in running at least adminio-api in my test environment, i like it's simplicity and RESTfull approach.

**Comment by rzrbld** [comment]
@Niggl1999 thanks, i just checked and seems that version is not supported, i try to fix that in the next  one - two days

**Comment by rzrbld** [comment]
@Niggl1999 since version of minio that you have is too old, modern minio libs don't support it. so you have two ways to solve that:
- if it possible - you can try to update minio, since than you be able to use latest adminio or minio console besides new minio features like: tags, quotas and new policies
- if you can't update you still able to use `rzrbld/adminio-ui:release-0.63` and `rzrbld/adminio-api:release-0.4` images with your current minio version

**Comment by Niggl1999** [comment]
Thank you very much, then i'll give it another go in 1-2 weeks :)
